
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.tfc]
			acacia = true
			ash = true
			aspen = true
			birch = true
			blackwood = true
			chestnut = true
			douglas_fir = true
			hickory = true
			kapok = true
			mangrove = true
			maple = true
			oak = true
			palm = true
			pine = true
			rosewood = true
			sequoia = true
			spruce = true
			sycamore = true
			white_cedar = true
			willow = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			couch = true
			shelf = true
			nightstand = true
			table = true
			chair = true
			drawer = true
			cupboard = true
			pillar_trim = true
			dining_bench = true
			side_table = true
			bench = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.mcwdoors]
			nether_door = true
			stable_head_door = true
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			cottage_door = true
			four_panel_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			beach_door = true
			barn_door = true
			mystic_door = true
			whispering_door = true
			waffle_door = true
			japanese_door = true
			bark_glass_door = true
			classic_door = true
			stable_door = true
			modern_door = true

		[entries.wood_type.mcwtrpdoors]
			ranch_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			beach_trapdoor = true
			swamp_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			glass_trapdoor = true
			whispering_trapdoor = true
			barred_trapdoor = true
			blossom_trapdoor = true
			tropical_trapdoor = true
			cottage_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			mystic_trapdoor = true
			barrel_trapdoor = true

