
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.tfc]
			acacia = true
			ash = true
			aspen = true
			birch = true
			blackwood = true
			chestnut = true
			douglas_fir = true
			hickory = true
			kapok = true
			mangrove = true
			maple = true
			oak = true
			palm = true
			pine = true
			rosewood = true
			sequoia = true
			spruce = true
			sycamore = true
			white_cedar = true
			willow = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			couch = true
			shelf = true
			nightstand = true
			table = true
			chair = true
			drawer = true
			cupboard = true
			pillar_trim = true
			dining_bench = true
			side_table = true
			bench = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window = true
			window_pane = true

